### ISSUE TITLE
Dashboard challenge matches 

### ISSUE THREAD

**Issue by mikekammes** [PastyPurpleTrolls/game-contest-server#12]
If the match had rounds simulated by the system then the "rounds" come in as the matches. This just means that all five dashboard spots will be taken by the last 5 rounds of the most recent match.

**Comment by j-mathews** [comment]
Challenge match is actually creating 5 matches of 5 rounds (if you select 5 rounds) so it is not a bug in the dashboard, but in the challenge player

**Comment by geisler** [comment]
Fixed in f623868f8a738fc99c827e2790435dc858ec73d0
