### ISSUE TITLE
Look at criteria for being able to delete a referee

### ISSUE THREAD

**Issue by johnluscombe** [PastyPurpleTrolls/game-contest-server#136]
The criteria for being able to delete a referee, found under the "deletable?" method in the referee.rb model, seems like it needs to be redone. For example, an admin should be able to delete the referee.

**Comment by geisler** [comment]
Yes, the admin should be able to delete a referee, but we still want to maintain the hard constraint that the referee cannot have any contests.  Once they are there, we don't want to delete a referee and lose historical data associated with any of those contests.
