### ISSUE TITLE
Saving Rounds to the DB

### ISSUE THREAD

**Issue by ZachAlford** [PastyPurpleTrolls/game-contest-server#23]
In app/model/round.rb, the following line might be necessary

```
validates :players, presence: true
```

Currently, it is possible to save a round to the database without that round having associated players, which would be incorrect. However, this brings the issue of how do you save a round to the database in the first place, and I did not know what to do about this.

**Comment by BoringCode** [comment]
Not every validation can be performed in the model. 

Basically we would have a chicken and egg scenario where you can't create a player_round without a round but you can't create a round without player_rounds. For this reason, this line should not be added to the round model. Rather we should enforce this restriction in the application logic (namely exec_environment/match_runner.rb)

**Comment by McSkivv** [comment]
This is currently a non-issue.  There is no set of circumstances where this occurs in production code.  In a number of places there are checks to make sure that a round isn't played with 0 players.
