### ISSUE TITLE
Players break things badly if their names include spaces?

### ISSUE THREAD

**Issue by geisler** [PastyPurpleTrolls/game-contest-server#27]
What happens when a player name includes a space?  For example, "The Best Player Ever!!!"

**Comment by McSkivv** [comment]
So far through extensive manual testing with a player with a space in the name, no current issues seem to exist.  An automated test will need to be written, but all such tests using Guess-W are currently failing due to Guess-W's brokenness.

**Comment by McSkivv** [comment]
All of my testing this month has included players with spaces in their names.  No issue exists here.
