### ISSUE TITLE
Throw errors when creating invalid tournament

### ISSUE THREAD

**Issue by BoringCode** [PastyPurpleTrolls/game-contest-server#3]
Certain tournament types (like round robin) assume 2 players in a match. But the ref may require a different number of players. This can cause errors to be silently thrown when creating new matches in the daemon.

We need to either disable invalid tournament types, or properly display errors to the user when creating the tournament.

**Comment by McSkivv** [comment]
You can currently create tournaments with no players.  Any way you slice it, that needs to be fixed.

**Comment by McSkivv** [comment]
This is actually redundant.  Another open issue better describes the error.
